apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-prod.yml convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: saevis-web
  name: saevis-web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: saevis-web
    spec:
      containers:
      - image: saevis-web
        name: saevis-web
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
