/**
 * Saevis
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { Content } from './content';


export interface Topic { 
    id?: number;
    title: string;
    content?: Array<Content>;
    createdAt?: Date;
    updatedAt?: Date;
}